export ZSH=~/.zsh

# Load all of the config files in our zsh folder that end in .zsh
for config_file ($ZSH/conf/*.zsh) source $config_file

# Add the following to your zshrc to access the online help
unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/helpfiles

print -Pn "\e]0; %n@%m: %~\a"   # terminal title


# Python development stuff

# to make pipenv available
export PATH=$PATH:$HOME/Library/Python/3.7/bin

# make pipenv create the virtualenv in the project's directory
export PIPENV_VENV_IN_PROJECT=1